In [13]:
import numpy as np

In [26]:
def indicators(x, endpts):
    '''
    if x value is inside the bound, return 1. Otherwise, return 0

    Require:
        x, left_bound, right_bound must have the same dimension

    Parameters: 

            x: m x n vector representing the index of point to check (Time dimension should be excluded)

            endpts: 2d (n x 2) array of index. First dimension is all the spatial dimensions, and second dimension are 
                    left and right bound of the subdomain in terms of index

    `return: 
            1 or 0, should be clear enough
    '''
    print(x)
    for i in range(len(endpts)):
        np.add(x[i], endpts[i][0], out=x[i])
    print(x)
    for i in range(len(endpts)):
        np.subtract(x[i], endpts[i][1], out=x[i])
    print(x)    

In [15]:
x = np.array([[1,2],[3,4],[5,6]])

In [16]:
print(x)
print(x.flatten())

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [17]:
y = np.array([[3,4,5],[1,3,5],[3,5,7]])
print(y)

[[3 4 5]
 [1 3 5]
 [3 5 7]]


In [27]:
indicators(y, x)

[[ 2  3  4]
 [ 2  4  6]
 [ 6  8 10]]
[[ 3  4  5]
 [ 5  7  9]
 [11 13 15]]
[[1 2 3]
 [1 3 5]
 [5 7 9]]


In [19]:
len(y)

3

In [36]:
upper_limit = 5
lower_limit = 1
a = np.array([1,2,3,4,5])
your_mask = np.abs(a- 0.5*(upper_limit+lower_limit))<0.5*(upper_limit-lower_limit)

In [37]:
your_mask

array([False,  True,  True,  True, False])

In [42]:

b = np.linspace(1,100,10**9)

In [39]:
upper_limit = 5
lower_limit = 1
your_mask = np.abs(b- 0.5*(upper_limit+lower_limit))<0.5*(upper_limit-lower_limit)

In [41]:
print(your_mask)
len(your_mask)

[False  True  True ... False False False]


100000000