In [162]:
import numpy as np

In [163]:
def indicators(x, endpts):
    '''
    if x value is inside the bound, return 1. Otherwise, return 0

    Require:
        x, left_bound, right_bound must have the same dimension

    Parameters: 

            x: m x n vector representing the index of point to check (Time dimension should be excluded)

            endpts: 2d (n x 2) array of index. First dimension is all the spatial dimensions, and second dimension are 
                    left and right bound of the subdomain in terms of index

    `return: 
            1 or 0, should be clear enough
    '''
    print(x)
    for i in range(len(endpts)):
        np.add(x[i], endpts[i][0], out=x[i])
    print(x)
    for i in range(len(endpts)):
        np.subtract(x[i], endpts[i][1], out=x[i])
    print(x)    

In [173]:
def setup_subdomains(spatial_grid, K):
    """Setup subdomains for nonlocal computation

        Output format: A list of ndim elements containing lists of bounds of subdomains. In a 2D
        case, an example would be [[[0, 1], [2, 4], [5, 9]], [[0, 4], [5, 12]]].
        Note that the subdomains are uniform in each dimension.
    """
#       spatial grid is this 2D tensor that stores the grid. 
#       We split each dimension into K (mostly) equally sized subdomains, where K is a parameter. 
#       There will be a total of K^ndim subdomains 
    created = []
    bounds = []
#     -1 to adjust for the last dimension, which indicates feature.
    for i in np.arange(np.array(spatial_grid).ndim):
#         does spatio-temporal grid have to have the same number of points in each spatial dimension?
        print(length)
        length = np.shape(spatial_grid)[0]
    
#         if length//K[i] < 2:
# #             replace this with warning or break point
#             print("Warning: too many subdomains created in axis", i)
        
#       Calculate the length for each subdomain 
        subdomain_length = length//K[i]
        remain = length % K[i]
        size = np.multiply(np.ones(subdomain_length), K[i])
        size = np.concatenate((np.add(size[0:remain], 1), size[remain:]))
        bound = np.cumsum(size)
        bounds.append(bound)
        print(size)
    return bounds

In [174]:
spatial_grid = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6]], dtype = object)
K = [4, 3, 2]

In [175]:
a = setup_subdomains(spatial_grid, K)
a

UnboundLocalError: local variable 'length' referenced before assignment

In [165]:
def nd_iterator(index, K):
    '''
    index: the 1D index of the nd item to recover
    K: number of items per dimension, corresponding to each of the n dimensions.
    
    return:
    nd index of the item with 1D index to be "index"
    '''
    nd_index = [index % K[0]]
    dividor = 1
    remaining_index = index
    for i in np.arange(len(K)-1):
        remaining_index -= nd_index[i]*dividor
        dividor *= K[i]
        this_index = remaining_index // dividor % K[i+1]
        nd_index.append(this_index)
    return nd_index
def subdomain_iterator(index, bounds, K):
    '''
    bounds: subdomain dividor, in standard setup_subdomains format
    nd_index: nd index of a specific subdomain, in nd_iterator standard output format.
    
    return:
    boundary of that subdomain in standard nonlocal format.
    '''
    nd_index = nd_iterator(index, K)
    bound = []
    for i in np.arange(len(nd_index)):
        if nd_index[i] == 0:
            bound.append([0, bounds[i][0]-1])
        else:
            bound.append([bounds[i][nd_index[i]-1], bounds[i][nd_index[i]]-1])
    
    return np.reshape(bound, (len(nd_index), 2))

In [166]:
spatial_grid = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6]], dtype = object)
K = [4, 3, 2]

In [167]:
print(spatial_grid)

[list([1, 2, 3, 4, 5, 6, 7]) list([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
 list([1, 2, 3, 4, 5, 6])]


In [168]:
np.shape(spatial_grid)
print(np.shape(spatial_grid)[0])

3


In [169]:
a = setup_subdomains(spatial_grid, K)
a

[]


[array([], dtype=float64)]

In [170]:
subdomain_iterator(1, a, K)

IndexError: index 0 is out of bounds for axis 0 with size 0

In [ ]:
a

[array([2, 4, 6, 7]), array([3, 5, 7])]

In [ ]:
a = [1,2,3,4,5]
a = np.array(a)

In [ ]:
import numpy as np
np.array([5] * 3)

array([5, 5, 5])

In [ ]:
a = 5
b = np.array([0,1,2,3,4,5,6])
c = np.array([6,7])
# for j in np.arange(a):
#     b[j] += 1;
b

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
b = np.concatenate((np.add(b[0:a], 1), b[a:]))
b

array([1, 2, 3, 4, 5, 5, 6])

In [ ]:
b = np.concatenate((b[0:a], c))
b

array([0, 1, 2, 3, 4, 6, 7])

In [ ]:
print(x)
print(x.flatten())

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [ ]:
y = np.array([[3,4,5],[1,3,5],[3,5,7]])
print(y)

[[3 4 5]
 [1 3 5]
 [3 5 7]]


In [ ]:
indicators(y, x)

[[ 2  3  4]
 [ 2  4  6]
 [ 6  8 10]]
[[ 3  4  5]
 [ 5  7  9]
 [11 13 15]]
[[1 2 3]
 [1 3 5]
 [5 7 9]]


In [ ]:
len(y)

3

In [ ]:
upper_limit = 5
lower_limit = 1
a = np.array([1,2,3,4,5])
your_mask = np.abs(a- 0.5*(upper_limit+lower_limit))<0.5*(upper_limit-lower_limit)

In [ ]:
your_mask

array([False,  True,  True,  True, False])

In [ ]:

b = np.linspace(1,100,10**9)

In [ ]:
upper_limit = 5
lower_limit = 1
your_mask = np.abs(b- 0.5*(upper_limit+lower_limit))<0.5*(upper_limit-lower_limit)

In [ ]:
print(your_mask)
len(your_mask)

[False  True  True ... False False False]


100000000